apiVersion: apps/v1
kind: Deployment
metadata:
  name: esoft-portal

spec:
  replicas: 2
  selector:
    matchLabels:
      app: esoft-portal
  template:
    metadata:
      labels:
        app: esoft-portal
    spec:
      containers:
      - name: esoft-portal
        image: lodakins/esoft_portal:v.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: esoft-portal
spec:
  type: LoadBalancer 
  selector:
    app: esoft-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
