apiVersion: apps/v1
kind: Deployment
metadata:
  name: esoft-portal
  labels:
    app: esoft-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esoft_portal
  template:
    metadata:
      labels:
        app: esoft_portal
    spec:
      containers:
      - name: esoft_portal
        image: lodakins/esoft_portal:v.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 3111
---
apiVersion: v1
kind: Service
metadata:
  name: esoft_portal
spec:
  type: LoadBalancer 
  selector:
    app: esoft_portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3111