apiVersion: apps/v1
kind: Deployment
metadata:
  name: esoft-portal
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: esoft-portal
  template:
    metadata:
      labels:
        app: esoft-portal
    spec:
      containers:
      - name: esoft-portal
        image: lodakins/esoft_portal:v.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: esoft-portal
spec:
  type: LoadBalancer 
  selector:
    app: esoft-portal
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
