apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udadevopscluster1
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 40
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]
